#!/usr/bin/env bash
# shellcheck source=/dev/null
if [ -f "$HOME/.dotfiles/.lib/toolbox/utilities.sh" ]; then
    . "$HOME/.dotfiles/.lib/toolbox/utilities.sh"
else
    echo "Missing file: $HOME/.dotfiles/.lib/toolbox/utilities.sh"
    exit 1
fi
#if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
#  my_script "${@}"
#  exit $?
#fi
#export -f my_script
# ================================================================================================== #
trap '' SIGINT SIGQUIT SIGTERM
NO_ROOT
SET_TPUT
# ================================================================================================== #
DOSYNC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOSYNC_VERSION="v1.0.3"
TERM="xterm-256color"
GITOPT="-q"
GITSUB="--quiet"
GITSUBOPT="--quiet"
INSTALL_DOSYNC="${INSTALL_DOSYNC:-no}"
NO_TTY="${NOTTY:-no}"
PIPED="${PIPED:-no}"
CHSHZSH="${CHSHZSH:-chsh -s $(which zsh)}"
RELOAD_SHELL="${RELOAD_SHELL:-exec $SHELL -l}"
# SYNC ENVIRONMENT #
DOTFILES="$HOME/.dotfiles"
CUSTOM_SYNC="$DOTFILES/sync.custom"
SYNCFILE="$DOTFILES/sync.config"
BACKUP_DIR="$HOME/.backup"
XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_RUNTIME_DIR="/run/user/$(id -u)"
# ================================================================================================== #
PRE_START() {
    [[ ! -d "$XDG_CONFIG_HOME" ]] && mkdir -p "$XDG_CONFIG_HOME"
    [[ ! -d "$XDG_CACHE_HOME" ]] && mkdir -p "$XDG_CACHE_HOME"
}
EXECUTE() {
    echo "Proceed? [y/N]"
    read -r response
    case $response in
    y/Y) return 0 ;;
    *) exit 1 ;;
    esac
}
PRE_CHECKS() {
    if [ "${DOTFILES:-$HOME/.dotfiles}" != "$DOSYNC_DIR" ]; then
        MSG_ERR "Dotfiles directory different as expected"
    fi
}
HAS_TERMINAL() {
    [ -t 0 ]
}
IS_TTY() {
    HAS_TERMINAL
}
IS_PIPED() {
    ! [ -t 1 ]
}
IS_GIT() {
    if [[ ! -d .git ]]; then
        MSG_ERR "Not a git repository"
        exit 1
    fi
}
USAGE() {
    cat <<EOF
    -===============================================================================-
    DoSync: $DOSYNC_VERSION ||
    -===============================================================================-
    Options:
    -U | --pull       - Update dotfiles repository and submodules
    -D | --add        - Add all changes
    -C | --commit     - Commit changes
    -P | --push       - Push to repository
    -A | --all        - Add all changes, commit and push to repository
    -===============================================================================-
    -===============================================================================-
    -H | --help       - Show this help message
EOF
}
RM_BROKEN_LINKS() {
    #    MSG_INFO "Removing broken symlinks from $HOME"
    find "$HOME" -maxdepth 1 -name ".*" -type l | while read -r f; do if [ ! -e "$f" ]; then rm -f "$f"; fi; done
}
RM_BROKEN_LINKS_CONFIG() {
    #    MSG_INFO "Removing broken symlinks from $HOME/.config"
    find "$HOME/.config" -maxdepth 1 -name "*" -type l | while read -r f; do if [ ! -e "$f" ]; then rm -f "$f"; fi; done
}
INIT_LOCAL() {
    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
    IS_GIT
    git submodule $GITSUB update --init --recursive
    cd || return 0
}
GET_GIT_ORIGIN() {
    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
    if [[ -d .git ]]; then
        ORIGIN=$(git config -l | grep remote.origin.url | awk -F'=' '{print $2}')
    fi
    cd || return 0
}
GIT_PULL() {
    GET_GIT_ORIGIN
    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
    IS_GIT
    MSG_INFO "Pulling latest changes from $ORIGIN"
    git pull $GITOPT
    MSG_INFO "Pulling latest changes for submodules"
    # Required if a submodule origin changed
    git submodule "$GITSUBOPT" sync
    git submodule "$GITSUBOPT" foreach --recursive git fetch
    git submodule "$GITSUBOPT" update --init --recursive
    cd || return 0
}
GIT_COMMIT() {
    GET_GIT_ORIGIN
    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
    MSG_INFO "Committing latest changes to the repository"
    git commit -a $GITOPT
    cd || return 0
}
GIT_PUSH() {
    GET_GIT_ORIGIN
    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
    MSG_INFO "Pushing changes upstream to $ORIGIN" &&
        git push $GITOPT
    cd || return 0
}
GIT_ADD() {
    cd "$DOTFILES" || ERROR "Failed to enter dotfiles directory"
    git add .
    cd || return 0
}
GIT_CHECK_ALL() {
    GET_GIT_ORIGIN
    GIT_ADD
    GIT_COMMIT
    GIT_PUSH
}
GET_SYNCFILE() {
    if [[ ! -s $SYNCFILE ]]; then
        if [[ -s "$DOTFILES/sync.config" ]]; then
            SYNCFILE="$DOTFILES/sync.config"
        else
            MSG_ERR "File $DOTFILES/sync.config doesnt exist, exiting"
            exit 1
        fi
    fi
}
GET_FILES_LIST() {
    SRCFILES="$(sed -n '/\[files\]/,/\[endfiles\]/p' "$SYNCFILE" | grep -v '^\[.*files]' | grep -v '^#')"
    CONFIG_FILES="$(sed -n '/\[configfiles\]/,/\[endconfigfiles\]/p' "$SYNCFILE" | grep -v '^\[.*configfiles]' | grep -v '^#')"
    if [[ -z "$SRCFILES" ]]; then
        MSG_ERR "Specify files to sync in $DOTFILES/sync.config file"
    fi
    if [[ -z "$CONFIG_FILES" ]]; then
        MSG_INFO "No files specified to sync from $DOTFILES/config"
    fi
}
GET_FILE() {
    srcfile="$(echo "$file" | awk -F: '{print $1}')"
    dstfile="$(echo "$file" | awk -F: '{print $2}')"
    DOTSRC="${DOTFILES}/${srcfile}"
    srcconfig="$(echo "$config_file" | awk -F: '{print $1}')"
    dstconfig="$(echo "$config_file" | awk -F: '{print $2}')"
    CONFIG_DOTSRC="$DOTFILES/$srcconfig"

    if [[ $dstfile = "" ]]; then
        dstfile=".$(basename "$srcfile")"
    fi
    DOTFILE="${HOME}/${dstfile}"

    if [[ $dstconfig = "" ]]; then
        dstconfig="$(basename "$srcconfig")"
    fi
    CONFIG_DOTFILE="$HOME/.config/$dstconfig"
}
GET_OPTIONS() {
    if [ "$NO_TTY" = yes ]; then
        echo "No tty"
    fi
}
DO_OPTIONS() {
    if HAS_TERMINAL; then
        export TERM="xterm-256color"
    fi
    if ! IS_TTY; then
        NO_TTY=yes
    fi
    if IS_PIPED; then
        PIPED=yes
    fi
    while [ $# = 0 ]; do
        DO_ACTION
    done
    while [ $# -gt 0 ]; do
        case $1 in
        --unattended) NO_TTY=yes ;;
        -U | --pull)
            GIT_PULL
            ;;
        -D | --add)
            GIT_ADD
            ;;
        -C | --commit)
            GIT_COMMIT
            ;;
        -P | --push)
            GIT_PUSH
            ;;
        -A | --all)
            GIT_CHECK_ALL
            ;;
        -S | --sync)
            DO_ACTION
            ;;
        -H | --help)
            USAGE
            exit 0
            ;;
        *) ERROR "Unknown action, please see: 'dosync -H' for options." ;;
        esac
        shift
    done
    GET_OPTIONS "${@}"
}
DO_SYNC() {
    GET_SYNCFILE
    GET_FILES_LIST
    RM_BROKEN_LINKS_CONFIG
    for config_file in $CONFIG_FILES; do
        GET_FILE "$config_file"
        if [[ -e "$CONFIG_DOTFILE" ]] && [[ ! -L "$CONFIG_DOTFILE" ]]; then
            [[ ! -d "$BACKUP_DIR/config" ]] && mkdir -p "$BACKUP_DIR/config"
            CONFIG_BACKUP="$BACKUP_DIR/config/$(basename "$config_file")"
            MSG_INFO "$CONFIG_DOTFILE already exists, backing up -> $CONFIG_BACKUP"
            cp -r "$CONFIG_DOTFILE" "$CONFIG_BACKUP"
            rm -rf "$CONFIG_DOTFILE"
            ln -s "$CONFIG_DOTSRC" "$CONFIG_DOTFILE"
            MSG_OK "Symlinked: $CONFIG_DOTSRC -> $CONFIG_DOTFILE"
        elif [[ -e "$CONFIG_DOTFILE" ]]; then
            rm -f "$CONFIG_DOTFILE"
            ln -s "$CONFIG_DOTSRC" "$CONFIG_DOTFILE"
            MSG_OK "Symlinked: $CONFIG_DOTSRC -> $CONFIG_DOTFILE"
        else
            ln -s "$CONFIG_DOTSRC" "$CONFIG_DOTFILE"
            MSG_OK "Symlinked: $CONFIG_DOTSRC -> $CONFIG_DOTFILE"
        fi
    done
    RM_BROKEN_LINKS
    for file in $SRCFILES; do
        GET_FILE "$file"
        if [[ -e "$DOTFILE" ]] && [[ ! -L "$DOTFILE" ]]; then
            [[ ! -d "$BACKUP_DIR" ]] && mkdir -p "$BACKUP_DIR"
            BACKUP="$BACKUP_DIR/$(basename "$file")"
            MSG_INFO "$DOTFILE already exists, backing up -> $BACKUP"
            cp -r "$DOTFILE" "$BACKUP"
            rm -rf "$DOTFILE"
            ln -s "$DOTSRC" "$DOTFILE"
            MSG_OK "Symlinked: $DOTSRC -> $DOTFILE"
        elif [[ -e "$DOTFILE" ]]; then
            rm -f "$DOTFILE"
            ln -s "$DOTSRC" "$DOTFILE"
            MSG_OK "Symlinked: $DOTSRC -> $DOTFILE"
        else
            ln -s "$DOTSRC" "$DOTFILE"
            MSG_OK "Symlinked: $DOTSRC -> $DOTFILE"
        fi
        ${reset:-}
    done
}
DO_ACTION() {
    MSG_NOTE "Performing >>>> (sync.config)"
    DO_SYNC
    MSG_NOTE "Performing >>>> (sync.custom)"
    source "$CUSTOM_SYNC"
    exit 0
}
MAIN() {
    PRE_START
    TITLE "DoSync version: $DOSYNC_VERSION"
    DO_OPTIONS "${@}"
    exit 0
}
while true; do
    MAIN "${@}"
done
